$F32F#angelika_pimple_in_space#
$D8AD#bt_small_logo_gfx#
$DAFC#byte_7000_DAFC#
$F1E8#galaxy_end_gfx#
$BBB2#plan_B_gfx#
$C677#plan_C_gfx#
$CD93#plan_D_gfx#
$DB1E#starship_gfx#
$E892#starship_gfx2#
